import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {

    GET_USER_DETAILS: `${STATE_REDUCER_KEY}/GET_USER_PROFILE_DETAILS`,
    GET_USER_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/GET_USER_PROFILE_DETAILS_REQUEST`,
    GET_USER_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/GET_USER_PROFILE_DETAILS_SUCCESS`,
    GET_USER_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/GET_USER_PROFILE_DETAILS_FAILURE`,

    UPDATE_USER_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS`,
    UPDATE_USER_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS_REQUEST`,
    UPDATE_USER_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS_SUCCESS`,
    UPDATE_USER_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS_FAILURE`,


    UPLOAD_IMAGE: `${STATE_REDUCER_KEY}/UPLOAD_IMAGE`,
    UPLOAD_IMAGE_REQUEST: `${STATE_REDUCER_KEY}/UPLOAD_IMAGE_REQUEST`,
    UPLOAD_IMAGE_SUCCESS: `${STATE_REDUCER_KEY}/UPLOAD_IMAGE_SUCCESS`,
    UPLOAD_IMAGE_FAILURE: `${STATE_REDUCER_KEY}/UPLOAD_IMAGE_FAILURE`,

    POST_OTP: `${STATE_REDUCER_KEY}/POST_OTP`,
    POST_OTP_REQUEST: `${STATE_REDUCER_KEY}/POST_OTP_REQUEST`,
    POST_OTP_SUCCESS: `${STATE_REDUCER_KEY}/POST_OTP_SUCCESS`,
    POST_OTP_FAILURE: `${STATE_REDUCER_KEY}/POST_OTP_FAILURE`,

    POST_RESET_PASSWORD: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD`,
    POST_RESET_PASSWORD_REQUEST: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_REQUEST`,
    POST_RESET_PASSWORD_SUCCESS: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_SUCCESS`,
    POST_RESET_PASSWORD_FAILURE: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_FAILURE`
};

export const getUserDetails = createAction(ACTION_TYPES.GET_USER_DETAILS);
export const uploadProfileImage = createAction(ACTION_TYPES.UPLOAD_IMAGE);
export const updateUserDetails = createAction(ACTION_TYPES.UPDATE_USER_DETAILS);
