import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    DASHBOARD: `${STATE_REDUCER_KEY}/DASHBOARD`,
    DASHBOARD_REQUEST: `${STATE_REDUCER_KEY}/DASHBOARD_REQUEST`,
    DASHBOARD_SUCCESS: `${STATE_REDUCER_KEY}/DASHBOARD_SUCCESS`,
    DASHBOARD_FAILURE: `${STATE_REDUCER_KEY}/DASHBOARD_FAILURE`,

    RECENT_ACTIVITIES: `${STATE_REDUCER_KEY}/RECENT_ACTIVITIES`,
    RECENT_ACTIVITIES_REQUEST: `${STATE_REDUCER_KEY}/RECENT_ACTIVITIES_REQUEST`,
    RECENT_ACTIVITIES_SUCCESS: `${STATE_REDUCER_KEY}/RECENT_ACTIVITIES_SUCCESS`,
    RECENT_ACTIVITIES_FAILURE: `${STATE_REDUCER_KEY}/RECENT_ACTIVITIES_FAILURE`,

    GET_USER_DETAILS: `${STATE_REDUCER_KEY}/GET_USER_DETAILS`,
    GET_USER_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/GET_USER_DETAILS_REQUEST`,
    GET_USER_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/GET_USER_DETAILS_SUCCESS`,
    GET_USER_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/GET_USER_DETAILS_FAILURE`,

    POST_AUTHENTICATION_DETAILS: `${STATE_REDUCER_KEY}/POST_USER_DETAILS`,
    POST_AUTHENTICATION_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/POST_USER_DETAILS_REQUEST`,
    POST_AUTHENTICATION_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/POST_USER_DETAILS_SUCCESS`,
    POST_AUTHENTICATION_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/POST_USER_DETAILS_FAILURE`,

    POST_OTP: `${STATE_REDUCER_KEY}/POST_OTP`,
    POST_OTP_REQUEST: `${STATE_REDUCER_KEY}/POST_OTP_REQUEST`,
    POST_OTP_SUCCESS: `${STATE_REDUCER_KEY}/POST_OTP_SUCCESS`,
    POST_OTP_FAILURE: `${STATE_REDUCER_KEY}/POST_OTP_FAILURE`,

    POST_RESET_PASSWORD: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD`,
    POST_RESET_PASSWORD_REQUEST: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_REQUEST`,
    POST_RESET_PASSWORD_SUCCESS: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_SUCCESS`,
    POST_RESET_PASSWORD_FAILURE: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_FAILURE`,

    EVENT_SESSION_LOGGED: `${STATE_REDUCER_KEY}/EVENT_SESSION_LOGGED`,
    EVENT_SESSION_LOGGED_REQUEST: `${STATE_REDUCER_KEY}/EVENT_SESSION_LOGGED_REQUEST`,
    EVENT_SESSION_LOGGED_SUCCESS: `${STATE_REDUCER_KEY}/EVENT_SESSION_LOGGED_SUCCESS`,
    EVENT_SESSION_LOGGED_FAILURE: `${STATE_REDUCER_KEY}/EVENT_SESSION_LOGGED_FAILURE`,

    FETCH_COURSE_LIST: `${STATE_REDUCER_KEY}/FETCH_COURSE_LIST`,
    FETCH_COURSE_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COURSE_LIST_REQUEST`,
    FETCH_COURSE_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COURSE_LIST_SUCCESS`,
    FETCH_COURSE_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COURSE_LIST_FAILURE`,


    FETCH_FETCH_LEARNING: `${STATE_REDUCER_KEY}/FETCH_FETCH_LEARNING`,
    FETCH_FETCH_LEARNING_REQUEST: `${STATE_REDUCER_KEY}/FETCH_FETCH_LEARNING_REQUEST`,
    FETCH_FETCH_LEARNING_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_FETCH_LEARNING_SUCCESS`,
    FETCH_FETCH_LEARNING_FAILURE: `${STATE_REDUCER_KEY}/FETCH_FETCH_LEARNING_FAILURE`

};

export const dashboard = createAction(ACTION_TYPES.DASHBOARD);
export const fetchRecentActivity = createAction(ACTION_TYPES.RECENT_ACTIVITIES);
export const eventSessionLogged = createAction(ACTION_TYPES.EVENT_SESSION_LOGGED);
export const learningProgress = createAction(ACTION_TYPES.FETCH_FETCH_LEARNING);

export const fetchCourses = createAction(ACTION_TYPES.FETCH_COURSE_LIST);

