import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    ADD_PRODUCT: `${STATE_REDUCER_KEY}/ADD_PRODUCT`,
    ADD_PRODUCT_REQUEST: `${STATE_REDUCER_KEY}/ADD_PRODUCT_REQUEST`,
    ADD_PRODUCT_SUCCESS: `${STATE_REDUCER_KEY}/ADD_PRODUCT_SUCCESS`,
    ADD_PRODUCT_FAILURE: `${STATE_REDUCER_KEY}/ADD_PRODUCT_FAILURE`,

    VIEW_LECTURE: `${STATE_REDUCER_KEY}/VIEW_LECTURE`,
    VIEW_LECTURE_REQUEST: `${STATE_REDUCER_KEY}/VIEW_LECTURE_REQUEST`,
    VIEW_LECTURE_SUCCESS: `${STATE_REDUCER_KEY}/VIEW_LECTURE_SUCCESS`,
    VIEW_LECTURE_FAILURE: `${STATE_REDUCER_KEY}/VIEW_LECTURE_FAILURE`,

    FETCH_LECTURE_DURATION: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION`,
    FETCH_LECTURE_DURATION_REQUEST: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION_REQUEST`,
    FETCH_LECTURE_DURATION_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION_SUCCESS`,
    FETCH_LECTURE_DURATION_FAILURE: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION_FAILURE`


};

export const addProduct = createAction(ACTION_TYPES.ADD_PRODUCT);
export const fetchCurrentLecturePlaylist = createAction(ACTION_TYPES.VIEW_LECTURE);
export const fetchLectureDuration = createAction(ACTION_TYPES.FETCH_LECTURE_DURATION);
