import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    COURSE_PREVIEW: `${STATE_REDUCER_KEY}/COURSE_PREVIEW`,
    COURSE_PREVIEW_REQUEST: `${STATE_REDUCER_KEY}/COURSE_PREVIEW_REQUEST`,
    COURSE_PREVIEW_SUCCESS: `${STATE_REDUCER_KEY}/COURSE_PREVIEW_SUCCESS`,
    COURSE_PREVIEW_FAILURE: `${STATE_REDUCER_KEY}/COURSE_PREVIEW_FAILURE`,

    VIEW_LECTURE: `${STATE_REDUCER_KEY}/VIEW_LECTURE`,
    VIEW_LECTURE_REQUEST: `${STATE_REDUCER_KEY}/VIEW_LECTURE_REQUEST`,
    VIEW_LECTURE_SUCCESS: `${STATE_REDUCER_KEY}/VIEW_LECTURE_SUCCESS`,
    VIEW_LECTURE_FAILURE: `${STATE_REDUCER_KEY}/VIEW_LECTURE_FAILURE`,

    FETCH_LECTURE_DURATION: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION`,
    FETCH_LECTURE_DURATION_REQUEST: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION_REQUEST`,
    FETCH_LECTURE_DURATION_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION_SUCCESS`,
    FETCH_LECTURE_DURATION_FAILURE: `${STATE_REDUCER_KEY}/FETCH_LECTURE_DURATION_FAILURE`


};

export const coursePreview = createAction(ACTION_TYPES.COURSE_PREVIEW);
export const fetchCurrentLecturePlaylist = createAction(ACTION_TYPES.VIEW_LECTURE);
export const fetchLectureDuration = createAction(ACTION_TYPES.FETCH_LECTURE_DURATION);
